
const DISBURSEMENTS = {
    LOAD: "REQUEST_DISBURSEMENTS_DATA",
    LOAD_SUCCESS: "RECEIVE_DISBURSEMENTS_DATA",
    POST_SUCCESS: "POST_DISBURSEMENTS_DATA",
    ADD_FROM_SEARCH_DATE: "FROM_SEARCH_DATE_DISBURSEMENTS",
    ADD_TO_SEARCH_DATE: "TO_SEARCH_DATE_DISBURSEMENTS",
    ADD_FILTER_CHECKBOXES: "ADD_FILTER_CHECKBOXES_DISBURSEMENTS"

};

export default DISBURSEMENTS;