
const SERVICES = {
    LOAD: "REQUEST_SERVICES_DATA",
    LOAD_SUCCESS: "RECEIVE_SERVICES_DATA",
    POST_SUCCESS: "POST_SERVICES_DATA",
    ADD_FROM_SEARCH_DATE: "FROM_SEARCH_DATE",
    ADD_TO_SEARCH_DATE: "TO_SEARCH_DATE",
};

export default SERVICES;